model:
  output_dim: 1
  batch_size: 32 
  dropout_rate: 0. # proportions de neurones à désactiver
  embedding_dim: 768 # dimension de l'embedding
  layer_dims: 
    - 256
    - 128
train:
    seed: 150 
    num_epochs: 32
    batch_size: 32
    learn_rate: 0.0001
    num_workers: 4
    weight_decay: 0.00001
    train_val_split: 0.85
vectorizer:
  max_length: 258
  dictionnary_path: ./out/model.dict