model:
  output_dim: 1
  dropout_rate: 0.3
  layer_dims:
    - 256
    - 128
  embedding_dim: 128

train:
  seed: 42
  num_epochs: 60
  batch_size: 32
  learn_rate: 0.001
  num_workers: 0
  weight_decay: 0.0005
  train_val_split: 0.8
  lr_mode: min
  lr_factor: 0.1
  lr_patience: 5
  checkpoint_path: ./out/model.pt

embedding:
  embedding_dim: 128
  num_epochs: 100
  batch_size: 32
  learn_rate: 0.001
  weight_decay: 0.00001
  checkpoint_path: ./out/model.embedding.pt

vectorizer:
  max_length: 128
  dictionnary_path: ./out/model.dict
