model:
  output_dim: 1
  dropout_rate: 0.4
  embedding_dim: 512
  layer_dims: 
    - 256
    - 128
train:
    seed: 150
    num_epochs: 16
    batch_size: 4
    learn_rate: 0.0001
    num_workers: 0
    weight_decay: 0.00001
    train_val_split: 0.85
vectorizer:
  max_length: 258
  dictionnary_path: ./out/model.dict