train:
	sxm train --train "../cli-data/train.csv" --test "../cli-data/test.csv"

analyze-train-set:
	sxm analyze-train-set --train "../cli-data/train.csv"

install:
	poetry install

copy-venv:
	poetry env info --path | pbcopy